# Generated by Django 5.1.6 on 2025-03-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_alter_design_technical_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='hierarchy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
