# Generated by Django 5.1.6 on 2025-05-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_process_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
