# Generated by Django 5.1.6 on 2025-03-12 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_person_document'),
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.design')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('workshop_email', models.EmailField(max_length=254)),
                ('workshop_phone_number', models.CharField(max_length=20)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.person')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateTimeField()),
                ('expected_delivery', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('delivered_units', models.IntegerField()),
                ('observation', models.TextField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.batch')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.process')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.workshop')),
            ],
        ),
    ]
