# Generated by Django 5.1.6 on 2025-03-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='workshop_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
