# Generated by Django 5.1.6 on 2025-03-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_processassignment_status_alter_workshop_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processassignment',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
    ]
