# Generated by Django 5.1.6 on 2025-03-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_processassignment_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processassignment',
            name='delivered_units',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='processassignment',
            name='observation',
            field=models.TextField(null=True),
        ),
    ]
