# Generated by Django 5.1.6 on 2025-05-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_processassignment_delivered_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='final_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
