# Generated by Django 5.1.6 on 2025-05-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_batch_final_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=20),
        ),
    ]
