# Generated by Django 5.1.6 on 2025-05-13 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_batch_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processassignment',
            options={'get_latest_by': 'delivery_date'},
        ),
    ]
